language: php

php:
    - '7.2'
    - '7.4'

# cache vendor dirs
cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer install --prefer-dist --no-interaction

script:
    - vendor/bin/phpstan analyse -c phpstan.neon -l max src
    - vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no
